version: 2.1

# Define the jobs we want to run for this project
jobs:
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependancies
          command: yarn
      - run: yarn lint

# Orchestrate our job run sequence
workflows:
  lint:
    jobs:
      - lint
